"""Delete field update_at

Revision ID: a6c802128955
Revises: 47650f61247e
Create Date: 2024-03-29 10:15:15.741077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6c802128955'
down_revision: Union[str, None] = '47650f61247e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('information', 'update_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('information', sa.Column('update_at', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
