"""Delete text field

Revision ID: b3c8bd616e43
Revises: 4bda167d20b8
Create Date: 2024-03-28 19:53:18.060846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3c8bd616e43'
down_revision: Union[str, None] = '4bda167d20b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('information', 'text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('information', sa.Column('text', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
